language: python
python:
- '2.7'
- '3.5'
- '3.6'

os:
- linux

# blocklist
branches:
  except:
  - legacy
  - experimental
  - develop
  - tensorflow

cache: pip

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --set anaconda_upload no

install:
  - bash travis_install.sh

script:
- coverage run travis_tests.py

after_success:
  - codecov

deploy:
  - provider: pypi
    user: fdtomasi
    password:
      secure: RPxVhYOg6P4Q8mFWrUH7k1SIdoPMplxsrreItBC/GFFnMEzq7R3Is3gv+XWUJ2ced+i8+X42xKYQJL0P1kULCWvA6K26CNVmuAssOhv9rEFGh5om6J7Y2X7qu1pRd2z4iLKe4C2YVcLgNdMCyuIdj/B/TicRdYWdRVhP8gShfXs9pYwgweYrTvMnG0F7PP+hwrn3aDixcCBlumP3dRhmUP01y+GikgO+v5VQ0Z/OOp9EGG3I68/vdjpLHLwjZ8BAvWceSlVvjBs4OtjH5szbKzFqOyZKqISNdaIe47qtFjSDY3LbhZu2FNh20RpogoIFLFNgdJJIt0KWAyKkd0YjjS5S/eIWT/bFbfXnI+ohTJmgA9LtOhJ8F61WuU4VlaN8WeITvEUT0cTEDEnnKQmxhLwwyZFk/IHjn4AM2NG1Bz2Do2zkFiTWb00kDasDN1z+3D0h2Ndf9/DemhckPEJegACPGXUmzdqCrG1sMel3OC/E7xL/UDPTpI318RvSJ9VKj5H8pviBdygj45W5p10ZXnmxmEOL4UQ5Iw77pINwQOaxROy6u48o7dUTzxCbWyDV7MlRHz3rLi19fC7aBeVj1NPY08cRaFsHJPMMpeD/6YhHo+osYxX/ayEyB5eSzmpQI/8KsyTvD11Dysmd06qSTsTAAqPxDsgAcWkTz9gvxu0=
    distributions: sdist bdist_wheel
    on:
      repo: fdtomasi/regain
      tags: true
      python: '2.7'
  - provider: releases
    api_key:
      secure: IbzvHgN5aRUwSUcTdnnmLqAJw1DZz2InulgYheAT1CrUwepXWguppdD4zYnkhylZ283rNPHgeuyfIBl/x1SXQHqkyOXb5TjjhMU7t2iMM1M5NzZ8p5VsYcV8er3HkDj2br7/kgW0UdyHBaGHwgyLNULTBehCnK5zagvuY0A5M5vjljuJ7DPi/v/UtorBBqpY6/tJ7se+/Qy4XVrRyAxTkq+Nr3bTb742dERZLHyIDiv/kYEYQaMsHC/t4lPTTuZZsz1rs8C9/hi1+C8Dsjmo/nks46m2mmAaYwEGvM3bzBEFyF2o+IDrnV7JE0JhJHzEIEotKmVxG1AVntlbSyLyirZh6qqfLnLSqTYMynRlggNEhT4meOifc1g3f9KtZQtfO6y90ffhEVNpwVOGg7CVIiH1p4DiS01byT9H7bPH2LJyla3P6WG6gJx4jdEYcfv28NK0K7kk90vICKySv0LsCm/9iZlGcHSbd9O55U7sG8oQcXJdJfXYYqml2SBtOjjprI9mwdmvvsInAp3EkAi31+y8IMMPNba6/iv96WF3ZW2nez6l13kbZmC8tBl63TJb7gHYxHGER3T97VeYA7XmHd+va9qtfQ7/lngwJHJgFXm3C5h0QiK4guWGqqwDboluSOgz8zpxrhrzhtd3R/0zA7nASyKfnq+FdOV38Duxkrc=
    # file: build/regain_$(TRAVIS_TAG)
    skip_cleanup: true
    on:
      repo: fdtomasi/regain
      tags: true
  - provider: script
    script: bash deploy_anaconda.sh
    skip_cleanup: true
    on:
      repo: fdtomasi/regain
      tags: true

notifications:
  slack:
    rooms:
    - secure: I+CJQ9xJ7wXcVfJ33pWpWS16zhRDD1odSpCKINQMpTV9UEtCo7n9SmOwaKD/JRDkyW2eT2VwK5d86gzgEEDAiPk3+Kysx6nokp9tg22t0vZ6bdFHj/9N7Vqu3THZ0xWGik/WMdOh6bdM4TK2sJPiqX8L7GKFVDqBeNF5nL3qTHhAjpIl6juXlY8A2CNAtdsdzX0pGa4Q+1LIATs6ViXac6jaW4JLdOt2hXIrKR1S43gVIs3s2N9QZ06s0LXMux68bEQiW6/BHhs6FlAUmGv2KhmMhP4gZnKkcnw/B0sq8l/35S/A10vHZG9JuQzjzvOKBn1JMNt/LtiEca4CcxVwamWHFUvEPAkI0LHzv09DCFGgnu/o1ClAx3IMPik6kkDFHfqRemUsv3tJu+PMZfsOLmSK5e+TT5uTljPZq0MxTVun53JAx6ziBkuiI+gMT9j6wYXZ41P+rf5tTcUG6uhlfCqjypMPjTHK4wy6zGgPS1RelPMblLlFfpMgqDe/pL7iVkamxxURqtbchYDzF10FCY1p+xXOLyq9hXBAHaSEGKYWjjdRzI+s19YX8Ln25ytEFObKzgPp/tXu4sqR/DmBhb7t9CM7unpKf35kmTv6EJi6qCvSfi1Ncj/sOpaIJhKGD4OxnAjm8FARGM/sPDoZWJOk3m2n9bW+qKpmSe6BuDI=
    on_success: change
    on_failure: always
  email: false
